### ISSUE TITLE
A question about 

### ISSUE THREAD

**Issue by WinterLi1993** [OpenGene/MrBam#4]

**Comment by WinterLi1993** [comment]
Hi,
  how to get these values  as the below ? 
  “”sample  option    bam_size(mb)  vcf_lines  CPU_time(s)  Memory(mb)“

**Comment by ylxdzsw** [comment]
Run the [benchmark script](https://github.com/OpenGene/MrBam/blob/master/benchmark/run) in the benchmark folder should generate a file named "result.txt", which contains these information.
This script is written in Julia so you may need to [install it](http://julialang.org/downloads/) before running.

**Comment by WinterLi1993** [comment]
thank you , I will have a try later .

**Comment by WinterLi1993** [comment]
HI ,
    it's worked! thank you!
