### ISSUE TITLE
how to judge whether a read to support  an INDEL from VCF ?

### ISSUE THREAD

**Issue by WinterLi1993** [OpenGene/MrBam#5]
HI ,
    what's  the condition of the read to support INDEL(deletion or insertion) from VCF ??
    could you please show your code  ? 
    thank you!

**Comment by ylxdzsw** [comment]
Currently I simply check whether there is insertion/deletion observed in the same start position, ignoring what the exact bases inserted/deleted. The code about vcf is [here](https://github.com/OpenGene/MrBam/blob/master/MrBam/count.py#L6) and about bam is [here](https://github.com/OpenGene/MrBam/blob/master/MrBam/bam.py#L18). However, the bam part is buggy(insertions are ignored and softclips are misjudged as deletions) now and I'm still working on it.

**Comment by WinterLi1993** [comment]
thanks !
I sent an e-mail to you .
